### ISSUE TITLE
Issue when sending mail

### ISSUE THREAD

**Issue by ghost** [EsadCetiner/roundcube-rule-exclusions-plugin#1]
**CRS Version:** 3.3.5 (also with 4.0)
**ModSecurity Version:** [2.9.7](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.7)
**modsec audit logs:** _Posting when I get to access to server logs._
**Conflict with OWASP rule ID:** 921110 (_[REQUEST-921-PROTOCOL-ATTACK.conf](https://github.com/coreruleset/coreruleset/blob/v4.0/main/rules/REQUEST-921-PROTOCOL-ATTACK.conf#L34)_)
**What caused the false positive:** Sending mail which contains something with _get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock_ and having line break after that.

In example when I try to send message with Do you get this? and I enter line break after that, then message was not sent.
![image](https://github.com/EsadCetiner/roundcube-rule-exclusions-plugin/assets/151437067/d7b36e21-4775-4efa-81b4-7fb6f585b984)

**Comment by EsadCetiner** [comment]
Thank you for reporting this false positive, I can reproduce it and have a fix here: https://github.com/EsadCetiner/roundcube-rule-exclusions-plugin/pull/2

Please let me know if the pull request resolves your issue.

**Comment by WoolKIT** [comment]
> Thank you for reporting this false positive, I can reproduce it and have a fix here: #2
> 
> Please let me know if the pull request resolves your issue.

I'm original poster. Github didn't like something and account was deleted.

But yes, pull request resolves issue.
Opening another one soon.
