### ISSUE TITLE
Can't switch HTML/Plain text editor when textarea already have some content

### ISSUE THREAD

**Issue by VoosGit** [EsadCetiner/roundcube-rule-exclusions-plugin#3]
**Problem:**
Can't use HTML editor when textarea already have some content.
And when starting composing message with HTML editor, then also can't switch to classic (plain text).
Clear textarea switching works fine.

**CRS Version:** 4.0-RC2
**ModSecurity Version:** [2.9.7](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.7)
**Modsec audit logs:** Posting when I get to access to server logs.

<details>
  <summary>Logs</summary>
Soon.
</details>

Conflict with OWASP rule ID-s:
920420 ([REQUEST-920-PROTOCOL-ENFORCEMENT.conf](https://github.com/coreruleset/coreruleset/blob/v4.0/main/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf))
949110 ([REQUEST-949-BLOCKING-EVALUATION.conf](https://github.com/coreruleset/coreruleset/blob/v4.0/main/rules/REQUEST-949-BLOCKING-EVALUATION.conf))
980170 ([RESPONSE-980-CORRELATION.conf](https://github.com/coreruleset/coreruleset/blob/v4.0/main/rules/RESPONSE-980-CORRELATION.conf))

**What caused the false positive:**
When compose, reply or forwarding message and textarea already have some content and then switching to HTML editor.
Showing: Server Error! (error)

In web browser console: /?_task=utils&_action=html2text [HTTP/2 403] & /?_task=utils&_action=text2html [HTTP/2 403]

**Comment by EsadCetiner** [comment]
@VoosGit I've been able to reproduce the false positive and I've opened a pull request here: https://github.com/EsadCetiner/roundcube-rule-exclusions-plugin/pull/4

Please let me know if this fixed your issue

As a side note: don't ever disable rule 949110 and 980170. 980170 can provide useful information about any blocked attacks, and 949110 is the rule that will block requests in anomoly scoring mode, disabling 949110 will essentially disable CRS.

**Comment by VoosGit** [comment]
> @VoosGit I've been able to reproduce the false positive and I've opened a pull request here: #4
> 
> Please let me know if this fixed your issue
> 
> As a side note: don't ever disable rule 949110 and 980170. 980170 can provide useful information about any blocked attacks, and 949110 is the rule that will block requests in anomoly scoring mode, disabling 949110 will essentially disable CRS.

Now all working fine. Thanks :)

**Comment by EsadCetiner** [comment]
good to hear, feel free to open another issue if you still have problems.
