### ISSUE TITLE
Copy&paste leftover?

### ISSUE THREAD

**Issue by hydrapolic** [EsadCetiner/roundcube-rule-exclusions-plugin#6]
https://github.com/EsadCetiner/roundcube-rule-exclusions-plugin/blob/main/plugins/roundcube-rule-exclusions-before.conf#L17

```
    ver:'sogo-rule-exclusions-plugin/1.0.0',\
```

Should be roundcube-rule-exclusions-plugin probably

**Comment by EsadCetiner** [comment]
Thank you, that was meant to be ``roundcube-rule-exclusions-plugin``.
I've corrected the issue here https://github.com/EsadCetiner/roundcube-rule-exclusions-plugin/commit/2335b9a1e97e480700fad9b6ed442741cd009b7a

**Comment by hydrapolic** [comment]
Thanks!
